/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/rpdzkj/work/sdk/dds-test-demo/idl/Robot_controlcmd.idl
  Source: /home/rpdzkj/work/sdk/dds-test-demo/idl/Robot_controlcmd.hpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#ifndef DDSCXX__HOME_RPDZKJ_WORK_SDK_DDS_TEST_DEMO_IDL_ROBOT_CONTROLCMD_HPP_49B425EFAFB978AD6EAB4B7F190F3D32
#define DDSCXX__HOME_RPDZKJ_WORK_SDK_DDS_TEST_DEMO_IDL_ROBOT_CONTROLCMD_HPP_49B425EFAFB978AD6EAB4B7F190F3D32

#include <utility>
#include <ostream>
#include <cstdint>
#include <array>

namespace RobotControlCmd
{
class ControlCmd
{
private:
 std::array<double, 2> axes_ = { };
 int32_t action_ = 0;
 uint16_t data_ = 0;

public:
  ControlCmd() = default;

  explicit ControlCmd(
    const std::array<double, 2>& axes,
    int32_t action,
    uint16_t data) :
    axes_(axes),
    action_(action),
    data_(data) { }

  const std::array<double, 2>& axes() const { return this->axes_; }
  std::array<double, 2>& axes() { return this->axes_; }
  void axes(const std::array<double, 2>& _val_) { this->axes_ = _val_; }
  void axes(std::array<double, 2>&& _val_) { this->axes_ = std::move(_val_); }
  int32_t action() const { return this->action_; }
  int32_t& action() { return this->action_; }
  void action(int32_t _val_) { this->action_ = _val_; }
  uint16_t data() const { return this->data_; }
  uint16_t& data() { return this->data_; }
  void data(uint16_t _val_) { this->data_ = _val_; }

  bool operator==(const ControlCmd& _other) const
  {
    (void) _other;
    return axes_ == _other.axes_ &&
      action_ == _other.action_ &&
      data_ == _other.data_;
  }

  bool operator!=(const ControlCmd& _other) const
  {
    return !(*this == _other);
  }

};

std::ostream& operator<<(std::ostream& os, ControlCmd const& rhs);

} //namespace RobotControlCmd

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::RobotControlCmd::ControlCmd>::getTypeName()
{
  return "RobotControlCmd::ControlCmd";
}

template <> constexpr bool TopicTraits<::RobotControlCmd::ControlCmd>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPELIB
template<> constexpr unsigned int TopicTraits<::RobotControlCmd::ControlCmd>::type_map_blob_sz() { return 314; }
template<> constexpr unsigned int TopicTraits<::RobotControlCmd::ControlCmd>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::RobotControlCmd::ControlCmd>::type_map_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x67,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x1a,  0x06,  0xcb,  0x54,  0x1a,  0x3a,  0xdd, 
 0xb5,  0xc8,  0x1f,  0x44,  0x90,  0xab,  0x82,  0x00,  0x4f,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x3f,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x16,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x02,  0x0a,  0x42,  0xb4,  0x7e,  0xed,  0x00,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x41,  0x8c,  0x55,  0x09,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x06,  0x8d,  0x77,  0x7f,  0x38,  0x00,  0xa3,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0xf3,  0x0e,  0x0a,  0x53,  0x8a,  0xd4,  0x71,  0x0c,  0xfc,  0x0c,  0x2a, 
 0x6c,  0xad,  0x97,  0x00,  0x8b,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x52,  0x6f,  0x62,  0x6f,  0x74,  0x43,  0x6f,  0x6e, 
 0x74,  0x72,  0x6f,  0x6c,  0x43,  0x6d,  0x64,  0x3a,  0x3a,  0x43,  0x6f,  0x6e,  0x74,  0x72,  0x6f,  0x6c, 
 0x43,  0x6d,  0x64,  0x00,  0x5b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x1f,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x02,  0x0a,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x61,  0x78,  0x65,  0x73,  0x00,  0x00,  0x00,  0x00, 
 0x15,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x61,  0x63,  0x74,  0x69,  0x6f,  0x6e,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x06,  0x00,  0x05,  0x00,  0x00,  0x00,  0x64,  0x61,  0x74,  0x61, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xf3,  0x0e,  0x0a, 
 0x53,  0x8a,  0xd4,  0x71,  0x0c,  0xfc,  0x0c,  0x2a,  0x6c,  0xad,  0x97,  0xf1,  0x1a,  0x06,  0xcb,  0x54, 
 0x1a,  0x3a,  0xdd,  0xb5,  0xc8,  0x1f,  0x44,  0x90,  0xab,  0x82, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::RobotControlCmd::ControlCmd>::type_info_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x1a,  0x06,  0xcb,  0x54,  0x1a,  0x3a,  0xdd,  0xb5,  0xc8,  0x1f,  0x44, 
 0x90,  0xab,  0x82,  0x00,  0x53,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xf3,  0x0e,  0x0a,  0x53,  0x8a,  0xd4,  0x71,  0x0c,  0xfc,  0x0c,  0x2a, 
 0x6c,  0xad,  0x97,  0x00,  0x8f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPELIB

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::RobotControlCmd::ControlCmd>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::RobotControlCmd::ControlCmd>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::RobotControlCmd::ControlCmd)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::RobotControlCmd::ControlCmd>();

namespace {
  static const volatile propvec &properties___RobotControlCmd__ControlCmd = get_type_props<::RobotControlCmd::ControlCmd>();
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::RobotControlCmd::ControlCmd& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.axes()[0], instance.axes().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.action()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.data()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::RobotControlCmd::ControlCmd& instance, key_mode key) {
  const auto &props = get_type_props<::RobotControlCmd::ControlCmd>();
  str.set_mode(cdr_stream::stream_mode::write, key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::RobotControlCmd::ControlCmd& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.axes()[0], instance.axes().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.action()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.data()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::RobotControlCmd::ControlCmd& instance, key_mode key) {
  const auto &props = get_type_props<::RobotControlCmd::ControlCmd>();
  str.set_mode(cdr_stream::stream_mode::read, key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::RobotControlCmd::ControlCmd& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.axes()[0], instance.axes().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.action()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.data()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::RobotControlCmd::ControlCmd& instance, key_mode key) {
  const auto &props = get_type_props<::RobotControlCmd::ControlCmd>();
  str.set_mode(cdr_stream::stream_mode::move, key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::RobotControlCmd::ControlCmd& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.axes()[0], instance.axes().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.action()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.data()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::RobotControlCmd::ControlCmd& instance, key_mode key) {
  const auto &props = get_type_props<::RobotControlCmd::ControlCmd>();
  str.set_mode(cdr_stream::stream_mode::max, key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX__HOME_RPDZKJ_WORK_SDK_DDS_TEST_DEMO_IDL_ROBOT_CONTROLCMD_HPP_49B425EFAFB978AD6EAB4B7F190F3D32
